# Generated by Django 4.2.7 on 2026-01-21 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Summary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('text', models.TextField()),
                ('source_url', models.URLField()),
                ('type', models.CharField(choices=[('article', 'Article'), ('video', 'Video'), ('document', 'Document')], max_length=20)),
                ('preLength', models.IntegerField()),
                ('postLength', models.IntegerField()),
                ('preWords', models.IntegerField()),
                ('postWords', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
