# Generated by Django 4.2.7 on 2026-01-21 21:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='summary',
            old_name='source_url',
            new_name='source',
        ),
        migrations.RenameField(
            model_name='summary',
            old_name='text',
            new_name='summary',
        ),
        migrations.AddField(
            model_name='summary',
            name='keyPoints',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='summary',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='summaries', to=settings.AUTH_USER_MODEL),
        ),
    ]
